# Login
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "admin",
  "password": "pwd"
}
###

POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "up",
  "password": "pwd"
}
###

# Checking if user is still logged-in
GET http://localhost:3001/api/sessions/current
###

# Execute Log Out
DELETE http://localhost:3001/api/sessions/current
###

#-----------Create link--------------
POST http://localhost:3001/api/link
content-type: application/json

{
  "firstDoc": 3,
  "secondDoc": [ {"id": 2, "relationship": "Update"},{"id": 4, "relationship": "Update"},{"id": 1, "relationship": "Update"}]
}
###

#-----------Get zone--------------
GET http://localhost:3001/api/zones
###

GET http://localhost:3001/api/document/zone/0
###

#-----------Insert zone--------------
POST http://localhost:3001/api/zone
content-type: application/json

{
  "coordinates":[
      [20.0777938, 67.8461752], [20.0959903, 67.8137874], [20.0959903, 67.8137874],[20.0777938, 67.8461752]
    ]
}
###

PUT http://localhost:3001/api/zone/4
content-type: application/json

{
  "coordinates":[
      [20.0777938, 67.8461752], [20.0959903, 67.8160000], [20.0959903, 67.8137874],[20.0959903, 67.8137876],[20.0777938, 67.8461752]
    ],
    "document": true
}
###

POST http://localhost:3001/api/resource/2
###