version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    env_file:
      - ../../.env  
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

volumes:
  mariadb_data: {}