version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - DB_HOST=${DB_HOST} 
        - DB_DATABASE=${DB_DATABASE}         
        - DB_USER=${DB_USER}                 
        - DB_PASSWORD=${DB_PASSWORD}         
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306" 

volumes:
  mariadb_data: {}